consul:
  command: agent -server -advertise $HOST_IP -bootstrap
  image: waieez/consul-ui:latest
  hostname: serv-00
  ports:
    - "$HOST_IP:8400:8400"
    - "$HOST_IP:8500:8500"
    - "$HOST_IP:8600:8600/udp"
    - "$HOST_IP:8600:8600"
  volumes:
    - /mnt/consul/config:/consul/config
registrator:
  image: gliderlabs/registrator:latest
  links:
    - consul
  command: -ip $HOST_IP -deregister on-success consul://consul:8500
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock
prometheus:
  command: '-config.file=/etc/prometheus/prometheus.yml -alertmanager.url=http://$HOST_IP:9093'
  image: prom/prometheus
  ports:
    - "$HOST_IP:9090:9090"
  links:
    - consul
  volumes:
    - ./prometheus:/etc/prometheus
exporter:
  command: -consul.server $HOST_IP:8500
  image: prom/consul-exporter
  ports:
    - "$HOST_IP:9107:9107"
  links:
    - consul
alertmanager:
  command: -config.file=/etc/alertmanager/config.yml
  image: prom/alertmanager
  ports:
    - "$HOST_IP:9093:9093"
  volumes:
    - ./alertmanager:/etc/alertmanager
api:
  image: waieez/fbforbots-api:latest
  ports: [80]
  environment:
    SERVICE_TAGS: metrics
    SERVICE_CHECK_HTTP: /health